package ht.kokoelma;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import ht.kokoelma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.19 16:59:39 // Generated by ComTest
 *
 */
public class ElokuvatTest {



  // Generated by ComTest BEGIN
  /** 
   * testAdd33 
   * @throws SailoException when error
   */
  @Test
  public void testAdd33() throws SailoException {    // Elokuvat: 33
    Elokuvat hen = new Elokuvat(); 
    assertEquals("From: Elokuvat line: 36", 0, hen.getLkm()); 
    hen.add(new Elokuva()); 
    assertEquals("From: Elokuvat line: 38", 1, hen.getLkm()); 
    hen.add(new Elokuva()); 
    assertEquals("From: Elokuvat line: 40", 2, hen.getLkm()); 
    while (hen.getLkm() <= hen.getMaksimi()-1)  {
    hen.add(new Elokuva()); 
    }
    hen.add(new Elokuva()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testGet92 
   * @throws IndexOutOfBoundsException when error
   */
  @Test
  public void testGet92() throws IndexOutOfBoundsException {    // Elokuvat: 92
    Elokuvat hen = new Elokuvat(); 
    try {
    hen.get(0); 
    fail("Elokuvat: 95 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    Elokuva h = new Elokuva(); 
    try {
    hen.add(h); 
    } catch (Exception e) {
    e.getMessage(); 
    }
    Elokuva k = new Elokuva(); 
    assertEquals("From: Elokuvat line: 103", true, hen.get(0) == h); 
    assertEquals("From: Elokuvat line: 104", false, hen.get(0) == k); 
    try {
    hen.get(1); 
    fail("Elokuvat: 105 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedosto191 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedosto191() throws SailoException {    // Elokuvat: 191
    Elokuvat test = new Elokuvat(); 
    test.testiTallennus(); 
    Elokuva yks = new Elokuva(); yks.rekisteroi(); yks.taytaTiedoilla(); 
    Elokuva kaks = new Elokuva(); kaks.rekisteroi(); kaks.taytaTiedoilla(); 
    test.tallenna("test"); 
    test.add(yks); test.add(kaks); 
    test.tallenna("test"); 
    test.alusta(); 
    test.lueTiedosto("test2"); 
    try {
    test.get(0); 
    fail("Elokuvat: 203 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); } // varmistaa että nyt on "auki" eri tiedosto
    test.alusta(); 
    test.lueTiedosto("test"); 
    assertEquals("From: Elokuvat line: 206", true, yks.toString().equals(test.get(0).toString())); 
    assertEquals("From: Elokuvat line: 207", true, kaks.toString().equals(test.get(1).toString())); 
    assertEquals("From: Elokuvat line: 208", false, kaks.toString().equals(test.get(0).toString()));  // varmistaa ettei läpimeno johdu testissä olevista ongelmista
    test.poistaTestitiedostot(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista294 
   * @throws SailoException when error
   */
  @Test
  public void testPoista294() throws SailoException {    // Elokuvat: 294
    Elokuvat el = new Elokuvat(); 
    Elokuva e = new Elokuva(); 
    Elokuva e2 = new Elokuva(); 
    e.asetaTiedot("" + 23, "Testi Elokuva", "" + 1999, "avainsanat"); 
    e2.asetaTiedot("" + 24, "Testi Elokuva", "" + 1999, "avainsanat"); 
    el.add(e); 
    el.add(e2); 
    assertEquals("From: Elokuvat line: 303", 2, el.getLkm()); 
    el.poista(e); 
    assertEquals("From: Elokuvat line: 305", 1, el.getLkm()); 
    el.poista(e); 
    assertEquals("From: Elokuvat line: 307", 1, el.getLkm()); 
    el.poista(e2); 
    assertEquals("From: Elokuvat line: 309", 0, el.getLkm()); 
  } // Generated by ComTest END
}