package ht.kokoelma;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.19 16:41:09 // Generated by ComTest
 *
 */
public class ElokuvaTest {



  // Generated by ComTest BEGIN
  /** testTaytaTiedoilla30 */
  @Test
  public void testTaytaTiedoilla30() {    // Elokuva: 30
    Elokuva e1 = new Elokuva(); 
    e1.taytaTiedoilla(); 
    assertEquals("From: Elokuva line: 33", true, e1.getNimi().matches("Interstellar [0-9]{4}")); 
    String v = "" + e1.getVuosi(); 
    assertEquals("From: Elokuva line: 35", true, v.matches("[0-9]{4}")); 
    assertEquals("From: Elokuva line: 36", "scifi, j‰nnitt‰v‰", e1.getAvainsanat()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi86 */
  @Test
  public void testRekisteroi86() {    // Elokuva: 86
    Elokuva test1 = new Elokuva(); 
    Elokuva test2 = new Elokuva(); 
    assertEquals("From: Elokuva line: 89", 0, test1.getEid()); 
    assertEquals("From: Elokuva line: 90", 0, test2.getEid()); 
    test1.rekisteroi(); 
    test2.rekisteroi(); 
    assertEquals("From: Elokuva line: 93", true, test2.getEid() - test1.getEid() == 1);  // testattava n‰in, koska testien suoritusj‰rjestyst‰ ei voi tiet‰‰
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString129 */
  @Test
  public void testToString129() {    // Elokuva: 129
    Elokuva test = new Elokuva(); 
    test.asetaTiedot("5", "elokuva", "1999", "vainsanat"); 
    assertEquals("From: Elokuva line: 132", true, "5|elokuva|1999|vainsanat|".equals(test.toString())); 
    assertEquals("From: Elokuva line: 133", false, "5|elokuva|1939|vansanat|".equals(test.toString())); 
  } // Generated by ComTest END
}