package ht.kokoelma;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ht.kokoelma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.19 16:39:37 // Generated by ComTest
 *
 */
public class HenkiloTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi37 */
  @Test
  public void testRekisteroi37() {    // Henkilo: 37
    Henkilo test1 = new Henkilo(); 
    Henkilo test2 = new Henkilo(); 
    assertEquals("From: Henkilo line: 40", 0, test1.getHid()); 
    assertEquals("From: Henkilo line: 41", 0, test2.getHid()); 
    test1.rekisteroi(); 
    test2.rekisteroi(); 
    assertEquals("From: Henkilo line: 44", true, test2.getHid() - test1.getHid() == 1);  // testattava näin, koska testien suoritusjärjestystä ei voi tietää
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTaytaTiedoilla60 */
  @Test
  public void testTaytaTiedoilla60() {    // Henkilo: 60
    Henkilo e1 = new Henkilo(); 
    e1.taytaTiedoilla(); 
    assertEquals("From: Henkilo line: 63", true, e1.getNimi().matches("Hannes Hoo [0-9]{4}")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString119 */
  @Test
  public void testToString119() {    // Henkilo: 119
    Henkilo test = new Henkilo(); 
    test.asetaTiedot("5", "Brad Pitt"); 
    assertEquals("From: Henkilo line: 122", true, "5|Brad Pitt|".equals(test.toString())); 
    assertEquals("From: Henkilo line: 123", false, "5|elokuva|1939|vansanat|".equals(test.toString())); 
  } // Generated by ComTest END
}