package ht.kokoelma;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ht.kokoelma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.25 16:34:43 // Generated by ComTest
 *
 */
public class KokoelmaTest {



  // Generated by ComTest BEGIN
  /** testSetHenkilo291 */
  @Test
  public void testSetHenkilo291() {    // Kokoelma: 291
    Kokoelma k = new Kokoelma(); 
    assertEquals("From: Kokoelma line: 293", 0, k.getHenkiloidenLkm()); 
    k.setHenkilo("Henkilö", 1, 1); 
    assertEquals("From: Kokoelma line: 295", 1, k.getHenkiloidenLkm()); 
    k.setHenkilo("Henkilö", 65, 54); 
    assertEquals("From: Kokoelma line: 297", 1, k.getHenkiloidenLkm()); 
    k.setHenkilo("Toinen Henkilö", 65, 54); 
    assertEquals("From: Kokoelma line: 299", 2, k.getHenkiloidenLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaHenkiloElokuvasta353 
   * @throws SailoException when error
   */
  @Test
  public void testPoistaHenkiloElokuvasta353() throws SailoException {    // Kokoelma: 353
    Relaatio r = new Relaatio(); 
    r.asetaTiedot("" + 1, "" + 2, "" + 3); 
    Henkilo h = new Henkilo(); 
    h.asetaTiedot("" + 2, "henkilo"); 
    Kokoelma k = new Kokoelma(); 
    k.add(r); 
    k.add(h); 
    Elokuva e = new Elokuva(); 
    e.asetaTiedot("" + 1, "ihan sama", "" + 1999, "anneainsanat"); 
    k.valitseElokuva(e); 
    assertEquals("From: Kokoelma line: 365", 1, k.getRelaatioidenLkm()); 
    try {
    k.poistaHenkiloElokuvasta("ei tämä henkilö", 3); 
    fail("Kokoelma: 366 Did not throw NullPointerException");
    } catch(NullPointerException _e_){ _e_.getMessage(); }
    assertEquals("From: Kokoelma line: 367", 1, k.getRelaatioidenLkm()); 
    k.poistaHenkiloElokuvasta("henkilo", 3); 
    assertEquals("From: Kokoelma line: 369", 0, k.getRelaatioidenLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoistaElokuva382 
   * @throws SailoException when error
   */
  @Test
  public void testPoistaElokuva382() throws SailoException {    // Kokoelma: 382
    Kokoelma k = new Kokoelma(); 
    Elokuva el = new Elokuva(); 
    el.asetaTiedot("" + 1, "nimi", "" + 1999, "avc"); 
    k.add(el); 
    Relaatio rel = new Relaatio(); 
    rel.asetaTiedot("" + 1, "" + 43, "" + 2); 
    k.add(rel); 
    assertEquals("From: Kokoelma line: 391", 1, k.getRelaatioidenLkm()); 
    assertEquals("From: Kokoelma line: 392", 1, k.getElokuvienLkm()); 
    k.poistaElokuva(el); 
    assertEquals("From: Kokoelma line: 394", 0, k.getElokuvienLkm()); 
    assertEquals("From: Kokoelma line: 395", 0, k.getRelaatioidenLkm()); 
  } // Generated by ComTest END
}