package ht.kokoelma;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import ht.kokoelma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.25 15:24:50 // Generated by ComTest
 *
 */
public class RelaatiotTest {



  // Generated by ComTest BEGIN
  /** 
   * testGet59 
   * @throws IndexOutOfBoundsException when error
   */
  @Test
  public void testGet59() throws IndexOutOfBoundsException {    // Relaatiot: 59
    Relaatiot rel = new Relaatiot(); 
    try {
    rel.get(0); 
    fail("Relaatiot: 62 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    Relaatio r = new Relaatio(); 
    rel.add(r); 
    assertEquals("From: Relaatiot line: 65", true, rel.get(0) == r); 
    assertEquals("From: Relaatiot line: 66", false, rel.get(0) == new Relaatio()); 
    try {
    rel.get(1); 
    fail("Relaatiot: 67 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAdd82 */
  @Test
  public void testAdd82() {    // Relaatiot: 82
    Relaatiot rel = new Relaatiot(); 
    assertEquals("From: Relaatiot line: 84", 0, rel.getLkm()); 
    rel.add(new Relaatio()); 
    assertEquals("From: Relaatiot line: 86", 1, rel.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedosto124 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedosto124() throws SailoException {    // Relaatiot: 124
    Relaatiot test = new Relaatiot(); 
    test.testiTallennus(); 
    Relaatio yks = new Relaatio(); 
    Relaatio kaks = new Relaatio(); 
    test.tallenna("test"); 
    test.add(yks); test.add(kaks); 
    test.tallenna("test"); 
    test.alusta(); 
    test.lueTiedosto("test2"); 
    try {
    test.get(0); 
    fail("Relaatiot: 136 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); } // varmistaa että nyt on "auki" eri tiedosto
    test.alusta(); 
    test.lueTiedosto("test"); 
    assertEquals("From: Relaatiot line: 139", true, yks.toString().equals(test.get(0).toString())); 
    assertEquals("From: Relaatiot line: 140", true, kaks.toString().equals(test.get(1).toString())); 
    test.poistaTestitiedostot(); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsiRelaatio223 */
  @Test
  public void testEtsiRelaatio223() {    // Relaatiot: 223
    Relaatio r = new Relaatio().asetaTiedot("" + 1, "" + 2, "" + 3); 
    Relaatio r2 = new Relaatio().asetaTiedot("" + 4, "" + 5, "" + 6); 
    Relaatiot rel = new Relaatiot(); 
    rel.add(r); 
    rel.add(r2); 
    Relaatio e = rel.etsiRelaatio(1, 2, 3); 
    assertEquals("From: Relaatiot line: 230", true, e == r); 
    assertEquals("From: Relaatiot line: 231", false, e == r2); 
    assertEquals("From: Relaatiot line: 232", null, rel.etsiRelaatio(7, 2, 3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista251 */
  @Test
  public void testPoista251() {    // Relaatiot: 251
    Relaatio r = new Relaatio().asetaTiedot("" + 1, "" + 2, "" + 3); 
    Relaatio r2 = new Relaatio().asetaTiedot("" + 4, "" + 5, "" + 6); 
    Relaatiot rel = new Relaatiot(); 
    rel.add(r); 
    rel.add(r2); 
    assertEquals("From: Relaatiot line: 257", 2, rel.getLkm()); 
    rel.poista(1, 2, 3); 
    assertEquals("From: Relaatiot line: 259", 1, rel.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista284 */
  @Test
  public void testPoista284() {    // Relaatiot: 284
    Relaatio r = new Relaatio().asetaTiedot("" + 1, "" + 2, "" + 3); 
    Relaatio r2 = new Relaatio().asetaTiedot("" + 4, "" + 5, "" + 6); 
    Relaatiot rel = new Relaatiot(); 
    rel.add(r); 
    rel.add(r2); 
    assertEquals("From: Relaatiot line: 290", 2, rel.getLkm()); 
    rel.poista(1, 3); 
    assertEquals("From: Relaatiot line: 292", 1, rel.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista316 */
  @Test
  public void testPoista316() {    // Relaatiot: 316
    Relaatio r2 = new Relaatio().asetaTiedot("" + 4, "" + 5, "" + 6); 
    Relaatio r = new Relaatio().asetaTiedot("" + 1, "" + 2, "" + 3); 
    Relaatio r3 = new Relaatio().asetaTiedot("" + 1, "" + 5, "" + 6); 
    Relaatiot rel = new Relaatiot(); 
    rel.add(r); 
    rel.add(r2); 
    rel.add(r3); 
    assertEquals("From: Relaatiot line: 324", 3, rel.getLkm()); 
    rel.poista(1); 
    assertEquals("From: Relaatiot line: 326", 1, rel.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsiRelaatio351 */
  @Test
  public void testEtsiRelaatio351() {    // Relaatiot: 351
    Relaatio r = new Relaatio().asetaTiedot("" + 1, "" + 2, "" + 3); 
    Relaatio r2 = new Relaatio().asetaTiedot("" + 4, "" + 5, "" + 6); 
    Relaatiot rel = new Relaatiot(); 
    rel.add(r); 
    rel.add(r2); 
    Relaatio e = rel.etsiRelaatio(1, 3); 
    assertEquals("From: Relaatiot line: 358", true, e == r); 
    assertEquals("From: Relaatiot line: 359", false, e == r2); 
    assertEquals("From: Relaatiot line: 360", null, rel.etsiRelaatio(7, 3)); 
  } // Generated by ComTest END
}