package ht.kokoelma;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ht.kokoelma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.19 15:33:14 // Generated by ComTest
 *
 */
public class RooliTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi88 */
  @Test
  public void testRekisteroi88() {    // Rooli: 88
    Rooli test1 = new Rooli(); 
    Rooli test2 = new Rooli(); 
    assertEquals("From: Rooli line: 91", 0, test1.getRid()); 
    assertEquals("From: Rooli line: 92", 0, test2.getRid()); 
    test1.rekisteroi(); 
    test2.rekisteroi(); 
    assertEquals("From: Rooli line: 95", true, test2.getRid() - test1.getRid() == 1);  // testattava n‰in, koska testien suoritusj‰rjestyst‰ ei voi tiet‰‰
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTaytaTiedoilla110 */
  @Test
  public void testTaytaTiedoilla110() {    // Rooli: 110
    Rooli e1 = new Rooli(); 
    e1.taytaTiedoilla(); 
    assertEquals("From: Rooli line: 113", true, e1.getRoolinNimi().matches("N‰yttelij‰ [0-9]{4}")); 
  } // Generated by ComTest END
}