package ht.kokoelma;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ht.kokoelma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.19 15:37:04 // Generated by ComTest
 *
 */
public class RoolitTest {



  // Generated by ComTest BEGIN
  /** 
   * testGet75 
   * @throws IndexOutOfBoundsException when error
   */
  @Test
  public void testGet75() throws IndexOutOfBoundsException {    // Roolit: 75
    Roolit rel = new Roolit(); 
    try {
    rel.get(4); 
    fail("Roolit: 78 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    Rooli r = new Rooli(); 
    rel.add(r); 
    assertEquals("From: Roolit line: 81", true, rel.get(3) == r); 
    assertEquals("From: Roolit line: 82", false, rel.get(0) == new Rooli()); 
    try {
    rel.get(5); 
    fail("Roolit: 83 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAdd96 */
  @Test
  public void testAdd96() {    // Roolit: 96
    Roolit rel = new Roolit(); 
    assertEquals("From: Roolit line: 98", 3, rel.getLkm());  // nykyisell‰‰n luo roolit luonnin yhteydess‰
    rel.add(new Rooli()); 
    assertEquals("From: Roolit line: 100", 4, rel.getLkm()); 
  } // Generated by ComTest END
}